In [2]:
import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
rotation_mat = np.zeros(shape=(3, 3))
#images = glob.glob('*.jpg')
for i in range(1,18,1):
    img = cv2.imread('./HandsOn/IMG_'+str(i)+'.jpg')
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6),None)
    #print(ret)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)
        
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,6), corners2,ret)
        cv2.imwrite('img'+str(i)+'.jpg',img)
        #cv2.imshow('img',img)
        #cv2.waitKey(500)

cv2.destroyAllWindows()
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
R = cv2.Rodrigues(rvecs[0], rotation_mat)[0]
P = np.column_stack((np.matmul(mtx,R),np.matmul(mtx,tvecs[0])))
P=P/P[2,3]


In [3]:
print('Camera Matrix:',mtx)
print('Rotaion Matrix:',R)
print('Projection Matrix:',P)

Camera Matrix: [[3.95667606e+03 0.00000000e+00 7.10247209e+02]
 [0.00000000e+00 3.88535462e+03 1.05592942e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Rotaion Matrix: [[-0.57797587  0.52617304 -0.62376744]
 [-0.68532909 -0.72793127  0.02097876]
 [-0.44302137  0.43961119  0.7813284 ]]
Projection Matrix: [[-1.36727181e+02  1.25827497e+02 -1.00546703e+02  1.38388797e+03]
 [-1.42403750e+02 -1.46204903e+02  8.61996341e+00  2.21644402e+03]
 [-2.32837381e-02  2.31045102e-02  4.10640367e-02  1.00000000e+00]]


In [4]:
#After Changing the focus
import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
rotation_mat = np.zeros(shape=(3, 3))
#images = glob.glob('*.jpg')
for i in range(1,18,1):
    img = cv2.imread('./HandsOn/IM_'+str(i)+'.jpg')
    
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6),None)
    #print(ret)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)
        
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,6), corners2,ret)
        cv2.imwrite('img'+str(i)+'.jpg',img)
        #cv2.imshow('img',img)
        #cv2.waitKey(500)

cv2.destroyAllWindows()
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
R = cv2.Rodrigues(rvecs[0], rotation_mat)[0]
P = np.column_stack((np.matmul(mtx,R),np.matmul(mtx,tvecs[0])))
P=P/P[2,3]


In [6]:
print('Camera Matrix:',mtx)
print('Rotation Matrix:',R)
#print('Translation Vector',tvecs)
print('Projection Matrix:',P)

Camera Matrix: [[3.97399370e+03 0.00000000e+00 1.49676828e+03]
 [0.00000000e+00 4.04303442e+03 4.80908369e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Rotation Matrix: [[-0.9816235  -0.14069016 -0.12892471]
 [ 0.01677175 -0.7365994   0.67612132]
 [-0.19008948  0.66153428  0.7254229 ]]
Projection Matrix: [[-2.54769234e+02  2.62385954e+01  3.49053627e+01  2.43468858e+03]
 [-1.43694200e+00 -1.61910918e+02  1.87627414e+02  1.06567677e+03]
 [-1.15706892e-02  4.02673913e-02  4.41562719e-02  1.00000000e+00]]
